-- Criação da tabela e importação dos dados
CREATE SCHEMA IF NOT EXISTS enem

CREATE TABLE IF NOT EXISTS enem.microdados_enem_2021
(
    "NU_INSCRICAO" numeric,
    "NU_ANO" numeric,
    "TP_FAIXA_ETARIA" numeric,
    "TP_SEXO" varchar,
    "TP_ESTADO_CIVIL" numeric,
    "TP_COR_RACA" numeric,
    "TP_NACIONALIDADE" numeric,
    "TP_ST_CONCLUSAO" numeric,
    "TP_ANO_CONCLUIU" numeric,
    "TP_ESCOLA" numeric,
    "TP_ENSINO" numeric,
    "IN_TREINEIRO" numeric,
	"CO_MUNICIPIO_ESC" numeric,
	"NO_MUNICIPIO_ESC" varchar, 
 	"CO_UF_ESC" numeric,
	"SG_UF_ESC" varchar, 
	"TP_DEPENDENCIA_ADM_ESC" numeric,
	"TP_LOCALIZACAO_ESC" numeric,
	"TP_SIT_FUNC_ESC" numeric,
	"CO_MUNICIPIO_PROVA" numeric,  
	"NO_MUNICIPIO_PROVA " varchar, 
	"CO_UF_PROVA" varchar,  
	"SG_UF_PROVA" varchar,  
	"TP_PRESENCA_CN" numeric,  
	"TP_PRESENCA_CH" numeric,  
	"TP_PRESENCA_LC" numeric,  
	"TP_PRESENCA_MT" numeric, 
	"CO_PROVA_CN" numeric,
	"CO_PROVA_CH" numeric,
	"CO_PROVA_LC" numeric,
	"CO_PROVA_MT" numeric,
	"NU_NOTA_CN" numeric,
	"NU_NOTA_CH" numeric,
	"NU_NOTA_LC" numeric,
	"NU_NOTA_MT " numeric,
	"TX_RESPOSTAS_CN" varchar, 
	"TX_RESPOSTAS_CH" varchar, 
	"TX_RESPOSTAS_LC" varchar, 
	"TX_RESPOSTAS_MT" varchar, 
	"TP_LINGUA" numeric, 
	"TX_GABARITO_CN" varchar, 
	"TX_GABARITO_CH" varchar,  
	"TX_GABARITO_LC" varchar,  
	"TX_GABARITO_MT" varchar,  
	"TP_STATUS_REDACAO" numeric,
	"NU_NOTA_COMP1" numeric,
	"NU_NOTA_COMP2" numeric,
	"NU_NOTA_COMP3" numeric,
	"NU_NOTA_COMP4" numeric,
	"NU_NOTA_COMP5" numeric,
	"NU_NOTA_REDACAO" numeric,
	"Q001" varchar, 
	"Q002" varchar,  
	"Q003" varchar,  
	"Q004" varchar, 
	"Q005" numeric,
	"Q006" varchar, 
	"Q007" varchar, 
	"Q008" varchar, 
	"Q009" varchar, 
	"Q010" varchar, 
	"Q011" varchar, 
	"Q012" varchar, 
	"Q013" varchar,  
	"Q014" varchar,  
	"Q015" varchar, 
	"Q016" varchar,  
	"Q017" varchar, 
	"Q018" varchar, 
	"Q019" varchar, 
	"Q020" varchar, 
	"Q021" varchar, 
	"Q022" varchar, 
	"Q023" varchar, 
	"Q024" varchar,  
	"Q025" varchar
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS enem.microdados_enem_2021
    OWNER to postgres;
	
-- Após a criação a importação dos dados foi feita pelo pgADmin 4
